api_version = "2023-07"

[[extensions]]
type = "ui_extension"
name = "Trust badges"
handle = "trust-badges"

[[extensions.targeting]]
module =  "./src/index.jsx"
target = "purchase.checkout.block.render"

[extensions.settings]

[[extensions.settings.fields]]
key = "title"
type = "single_line_text_field"
name = "Title"
description = "Why choose us?"

[[extensions.settings.fields]]
key = "layout"
type = "single_line_text_field"
name = "Layout"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["Grids","Rows"]'

[[extensions.settings.fields]]
key = "grids"
type = "single_line_text_field"
name = "Grids"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["1 column","2 columns", "3 columns", "4 columns"]'

[[extensions.settings.fields]]
key = "border"
type = "single_line_text_field"
name = "Border"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["none", "base", "dotted"]'

[[extensions.settings.fields]]
key = "image_width"
type = "single_line_text_field"
name = "Image width"
description = "Please specify percentage for image width"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["small","medium","large","extraLarge"]'

[[extensions.settings.fields]]
key = "padding"
type = "single_line_text_field"
name = "Padding"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["none","base", "tight", "extraTight", "loose", "extraLoose"]'

[[extensions.settings.fields]]
key = "alignment"
type = "single_line_text_field"
name = "Text alignment"
description = "Only works for classic style"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["start","center","end"]'

[[extensions.settings.fields]]
key = "trust_title1"
type = "single_line_text_field"
name = "Title 1"

[[extensions.settings.fields]]
key = "trust_description1"
type = "multi_line_text_field"
name = "Description 1"

[[extensions.settings.fields]]
key = "trust_icon1"
type = "single_line_text_field"
name = "Image url 1"
description = "Please paste the image url here. You can upload your icons/images in shopify files"

[[extensions.settings.fields]]
key = "trust_title2"
type = "single_line_text_field"
name = "Title 2"

[[extensions.settings.fields]]
key = "trust_description2"
type = "multi_line_text_field"
name = "Description 2"

[[extensions.settings.fields]]
key = "trust_icon2"
type = "single_line_text_field"
name = "Image url 2"
description = "Please paste the image url here. You can upload your icons/images in shopify files"


[[extensions.settings.fields]]
key = "trust_title3"
type = "single_line_text_field"
name = "Title 3"

[[extensions.settings.fields]]
key = "trust_description3"
type = "multi_line_text_field"
name = "Description 3"

[[extensions.settings.fields]]
key = "trust_icon3"
type = "single_line_text_field"
name = "Image url 3"
description = "Please paste the image url here. You can upload your icons/images in shopify files"


