# This file stores configurations for your Shopify app.

scopes = "unauthenticated_read_product_publications,unauthenticated_read_collection_publications,unauthenticated_read_product_listings,unauthenticated_read_product_tags,unauthenticated_read_selling_plans,unauthenticated_read_collection_listings,read_reports,read_orders,write_discounts"
