# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "checkout-plus"
client_id = "731d3f057b3dcdc6ec4edf58149401de"
application_url = "https://cfc6-103-28-132-234.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts, read_discounts, write_checkout_branding_settings"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://cfc6-103-28-132-234.ngrok-free.app/auth/callback",
  "https://cfc6-103-28-132-234.ngrok-free.app/auth/shopify/callback",
  "https://cfc6-103-28-132-234.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2023-04"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "recommendation-check.myshopify.com"
