# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Checkout plus dev"
client_id = "e4989bb8f01e4138aa83ddcb0a58beef"
application_url = "https://kb-dealtime-auditor-cemetery.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts, read_discounts, write_checkout_branding_settings"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://kb-dealtime-auditor-cemetery.trycloudflare.com/auth/callback",
  "https://kb-dealtime-auditor-cemetery.trycloudflare.com/auth/shopify/callback",
  "https://kb-dealtime-auditor-cemetery.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-checkout-ex.myshopify.com"
