# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Echo: Checkout Personalisation"
client_id = "49be3e74c8a62e808de0bbbea1c1d985"
application_url = "https://checkout-plus.fly.dev"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts, read_discounts, write_checkout_branding_settings,read_files"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://checkout-plus.fly.dev/auth/callback",
  "https://checkout-plus.fly.dev/auth/shopify/callback",
  "https://checkout-plus.fly.dev/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://checkout-plus.fly.dev/api/webhooks/customers/data_request"
  customer_data_request_url = "https://checkout-plus.fly.dev/api/webhooks/customers/data_request"
  shop_deletion_url = "https://checkout-plus.fly.dev/api/webhooks/customers/data_request"

[pos]
embedded = false
