api_version = "2023-07"


[[extensions]]
type = "ui_extension"
name = "Line item-change"
handle = "line-item-change"

[extensions.capabilities]
network_access = true
api_access = true


[[extensions.targeting]]
module =  "./src/index.jsx"
target = "purchase.checkout.cart-line-item.render-after"

