api_version = "2023-07"

[[extensions]]
type = "ui_extension"
name = "Checkout upsell"
handle = "checkout-upsell"

[[extensions.targeting]]
module =  "./src/index.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
network_access = true
block_progress = true
api_access = true

[extensions.settings]
[[extensions.settings.fields]]
key = "upsell_product"
type = "variant_reference"
name = "Upsell product"
