api_version = "2023-07"

[[extensions]]
type = "ui_extension"
name = "Image banner"
handle = "image-banner"

[[extensions.targeting]]
module =  "./src/index.jsx"
target = "purchase.checkout.block.render"

[extensions.settings]
[[extensions.settings.fields]]
key = "image_url"
type = "single_line_text_field"
name = "Image url"
description = "Please paste the image url here. You can upload your icons/images in shopify files"

[[extensions.settings.fields]]
key = "accessibility_description"
type = "single_line_text_field"
name = "Accessibility Description"

[[extensions.settings.fields]]
key = "lazyloading"
type = "boolean"
name = "Lazyloading"

[[extensions.settings.fields]]
key = "fit"
type = "boolean"
name = "Fit"
description = "Indicates how the image fits in its frame. Use if the image is not displayed at its intrinsic size to maintain the aspect ratio."

[[extensions.settings.fields]]
key = "border"
type = "boolean"
name = "Border"

[[extensions.settings.fields]]
key = "corner_radius"
type = "single_line_text_field"
name = "Corner Radius"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["small","base","large","fullyRounded", "none"]'