# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2023-10"

[[extensions]]
type = "ui_extension"
name = "Reviews"
handle = "reviews"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
[[extensions.settings.fields]]
    key = "title"
    type = "single_line_text_field"
    name = "Review 1 title"

[[extensions.settings.fields]]
    key = "number"
    type = "single_line_text_field"
    name = "Review 1 Number"

[[extensions.settings.fields]]
    key = "content"
    type = "multi_line_text_field"
    name = "Review 1 Content"

[[extensions.settings.fields]]
    key = "author"
    type = "single_line_text_field"
    name = "Review 1 Author"

[[extensions.settings.fields]]
    key = "show_review2"
    type = "boolean"
    name = "Show Review2"


[[extensions.settings.fields]]
    key = "title2"
    type = "single_line_text_field"
    name = "Review 2 title"

[[extensions.settings.fields]]
    key = "number2"
    type = "single_line_text_field"
    name = "Review 2 Number"

[[extensions.settings.fields]]
    key = "content2"
    type = "multi_line_text_field"
    name = "Review 2 Content"

[[extensions.settings.fields]]
    key = "author2"
    type = "single_line_text_field"
    name = "Review 2 Author"

