type = "checkout_ui_extension"
name = "AI Product recommendation"
api_version = "2023-04"


extension_points = [
  'Checkout::Dynamic::Render'
]

[capabilities]
api_access = true
network_access = true

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key-2"

# Read more on extension settings at https://shopify.dev/api/checkout-extensions/checkout/configuration
[settings]
  [[settings.fields]]
  key = "title"
  type = "single_line_text_field"
  name = "Title"
  description = "Eg: You might also like"

  [[settings.fields]]
  key = "recommendation_source"
  type = "single_line_text_field"
  name = "Recommendation source"
  description = "The product recommendation will based on this condition"
  [[settings.fields.validations]]
    name = "choices"
    value = '["First line item","Last line item","Most expensive item","Least expensive item"]'

  [[settings.fields]]
  key = "recommendation_algorithm"
  type = "single_line_text_field"
  name = "Recommendation algorithm"
  description = "How you want to recommend products"
  [[settings.fields.validations]]
    name = "choices"
    value = '["Related","Complementary"]'

  [[settings.fields]]
  key = "layout"
  type = "single_line_text_field"
  name = "Layout"
  [[settings.fields.validations]]
  name = "choices"
  value = '["Grids","Rows"]'

  [[settings.fields]]
  key = "grids"
  type = "single_line_text_field"
  name = "Grids"
  [[settings.fields.validations]]
  name = "choices"
  value = '["1 column","2 columns", "3 columns"]'

  [[settings.fields]]
  key = "limit"
  type = "single_line_text_field"
  name = "Products limit"
  description = "Number of products to recommend. You might not see more then 2 product on editor mode"

  [[settings.fields]]
  key = "show_variants"
  type = "boolean"
  name = "Show variants"
  description = "You can hide variant selector if you want to display only product"

  [[settings.fields]]
  key = "border"
  type = "boolean"
  name = "Border"

  [[settings.fields]]
  key = "padding"
  type = "single_line_text_field"
  name = "Padding"
  [[settings.fields.validations]]
    name = "choices"
    value = '["none","base", "tight", "extraTight", "loose", "extraLoose"]'

  [[settings.fields]]
  key = "add_to_cart_label"
  type = "single_line_text_field"
  name = "Add to cart label"

  [[settings.fields]]
  key = "button_style"
  type = "single_line_text_field"
  name = "Button style"
  [[settings.fields.validations]]
  name = "choices"
  value = '["primary","secondary","plain"]'
  
  [[settings.fields]]
  key = "button_size"
  type = "single_line_text_field"
  name = "Button size"
  [[settings.fields.validations]]
  name = "choices"
  value = '["extraSmall","small","base", "large", "extraLarge", "medium"]'
  
  [[settings.fields]]
  key = "include_price"
  type = "boolean"
  name = "Include price"
  description = "Add price in the add to cart label"