api_version = "2023-07"

[[extensions]]
type = "ui_extension"
name = "Count down timer"
handle = "count-down-timer"

[[extensions.targeting]]
module =  "./src/index.jsx"
target = "purchase.checkout.block.render"

[extensions.settings]
[[extensions.settings.fields]]
key = "title"
type = "single_line_text_field"
name = "Title"

[[extensions.settings.fields]]
key = "time_start_at"
type = "single_line_text_field"
name = "Countdown start at"
description = "Enter a number for the minutes countdown starts at: Eg: 10"

[[extensions.settings.fields]]
key = "reset_delay"
type = "single_line_text_field"
name = "Reset countdown delay"
description = "After countdown times out, wait this minutes before restarting"

[[extensions.settings.fields]]
key = "countdown_message"
type = "multi_line_text_field"
name = "Countdown message"
description = "Enter a short message for countdown or leave empty for default. Use $timer variable in the middle of your text to show the timer"

[[extensions.settings.fields]]
key = "countdown_message_after"
type = "single_line_text_field"
name = "Countdown message after timer"
description = "Enter a short message for countdown or leave empty for default. Use $timer variable in the middle of your text to show the timer"

[[extensions.settings.fields]]
key = "classic"
type = "boolean"
name = "Classic"
description = "The classic style will change the design of countdown"

[[extensions.settings.fields]]
key = "status"
type = "single_line_text_field"
name = "Status"

[[extensions.settings.fields.validations]]
name = "choices"
value = '["accent","subdued","info","success","warning","critical"]'

[[extensions.settings.fields]]
key = "alignment"
type = "single_line_text_field"
name = "Text alignment"
description = "Only works for classic style"

[[extensions.settings.fields.validations]]
name = "choices"
value = '["start","center","end"]'

[[extensions.settings.fields]]
key = "fontsize"
type = "single_line_text_field"
name = "Text size"

[[extensions.settings.fields.validations]]
name = "choices"
value = '["extraSmall","small","base", "medium", "large", "extraLarge"]'

[[extensions.settings.fields]]
key = "emphasis"
type = "single_line_text_field"
name = "Emphasis"

[[extensions.settings.fields.validations]]
name = "choices"
value = '["italic","bold", "base"]'
