type = "checkout_ui_extension"
name = "Count down timer"

extension_points = [
  'Checkout::Dynamic::Render'
]

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key-2"

# Read more on extension settings at https://shopify.dev/api/checkout-extensions/checkout/configuration
 [settings]
    [[settings.fields]]
    key = "title"
    type = "single_line_text_field"
    name = "Title"
    [[settings.fields]]
    key = "time_start_at"
    type = "single_line_text_field"
    name = "Countdown start at"
    description = "Enter a number for the minutes countdown starts at: Eg: 10"
    [[settings.fields]]
    key = "reset_delay"
    type = "single_line_text_field"
    name = "Reset countdown delay"
    description = "After countdown times out, wait this minutes before restarting"
    [[settings.fields]]
    key = "countdown_message"
    type = "multi_line_text_field"
    name = "Countdown message"
    description = "Enter a short message for countdown or leave empty for default. Use $timer variable in the middle of your text to show the timer"
    [[settings.fields]]
    key = "countdown_message_after"
    type = "single_line_text_field"
    name = "Countdown message after timer"
    description = "Enter a short message for countdown or leave empty for default. Use $timer variable in the middle of your text to show the timer"
    [[settings.fields]]
    key = "style"
    type = "single_line_text_field"
    name = "Style"
      [[settings.fields.validations]]
      name = "choices"
      value = '["info","success","warning","critical"]'
