
api_version = "2023-07"

[[extensions]]
type = "ui_extension"
name = "Feedback"
handle = "feeback"

[extensions.capabilities]
network_access = true
api_access = true

[[extensions.targeting]]
target = "customer-account.order-status.block.render"
module = "./src/Checkout.jsx"
export = "orderDetailsBlock"


[extensions.settings]
[[extensions.settings.fields]]
key = "question"
type = "single_line_text_field"
name = "Question text"
description = "This question will later on the order status page."

[[extensions.settings.fields]]
key = "question_description"
type = "single_line_text_field"
name = "Question description text"
description = "This we appear under the question to provide more information."

[[extensions.settings.fields]]
key = "option1"
type = "single_line_text_field"
name = "Option 1"
description = "The option for the question select option."

[[extensions.settings.fields]]
key = "option2"
type = "single_line_text_field"
name = "Option 2"
description = "The option for the question select option."

[[extensions.settings.fields]]
key = "option3"
type = "single_line_text_field"
name = "Option 3"
description = "The option for the question select option."

[[extensions.settings.fields]]
key = "option4"
type = "single_line_text_field"
name = "Option 4"
description = "The option for the question select option."

[[extensions.settings.fields]]
key = "option5"
type = "single_line_text_field"
name = "Option 5"
description = "The option for the question select option."

[[extensions.settings.fields]]
key = "option6"
type = "single_line_text_field"
name = "Option 6"
description = "The option for the question select option."

[[extensions.settings.fields]]
key = "option7"
type = "single_line_text_field"
name = "Option 7"
description = "The option for the question select option."

[[extensions.settings.fields]]
key = "option8"
type = "single_line_text_field"
name = "Option 8"
description = "The option for the question select option."

[[extensions.settings.fields]]
key = "option9"
type = "single_line_text_field"
name = "Option 9"
description = "The option for the question select option."

[[extensions.settings.fields]]
key = "option10"
type = "single_line_text_field"
name = "Option 10"
description = "The option for the question select option."
