api_version = "2023-07"

[[extensions]]
type = "ui_extension"
name = "Free gift"
handle = "free-gift"

[[extensions.targeting]]
module =  "./src/index.js"
target = "purchase.checkout.block.render"

[extensions.capabilities]
network_access = true
block_progress = true
api_access = true

[extensions.settings]
[[extensions.settings.fields]]
key = "title"
type = "single_line_text_field"
name = "Title"
description = "Eg: You might also like"

[[extensions.settings.fields]]
key = "add_to_cart_label"
type = "single_line_text_field"
name = "Add to cart label"
